FROM ghcr.io/elide-dev/tools/gvm19:latest

LABEL org.opencontainers.image.vendor=Elide
LABEL org.opencontainers.image.title="Elide Cloud: GVM19 Base"
LABEL org.opencontainers.image.description="GraalVM JDK19 tools for use with Elide Cloud apps"
LABEL org.opencontainers.image.version=alpha1
LABEL org.opencontainers.image.url=https://github.com/elide-dev/build-infra
LABEL org.opencontainers.image.base.name=elide-dev/runtime/gvm19
LABEL org.opencontainers.image.source=https://github.com/elide-dev/build-infra/blob/main/containers/gvm/Dockerfile
