name: "Build: Gradle (Android)"

on:
  workflow_call:
    inputs:
      ## Gradle action/target to run.
      action:
        description: "Action to run"
        default: "build"
        required: false
        type: string

      ## Gradle build flags to pass.
      flags:
        description: "Flags"
        required: false
        type: string

      ## Runner machine to use.
      runner:
        description: "Runner"
        required: false
        type: string

      ## Build step label to use.
      label:
        description: "Label"
        default: "Gradle"
        required: false
        type: string

      ## Whether to ignore errors.
      labs:
        description: "Labs"
        required: false
        type: boolean
        default: false

      ## Whether to install a regular JDK.
      install_jvm:
        description: "Install JDK"
        required: false
        type: boolean
        default: true

      ## JVM version to use.
      jvm:
        description: "JVM Version"
        required: false
        type: string
        default: '17'

      ## JVM distribution.
      jvm_dist:
        description: "JVM Variant"
        required: false
        type: string
        default: 'adopt-hotspot'

      ## Whether to setup the Android SDK.
      android:
        description: "Install Android SDK"
        required: false
        type: boolean
        default: true

      ## Whether to report coverage.
      coverage:
        description: "Report coverage"
        required: false
        default: false
        type: boolean

      ## Where to find the coverage report.
      coverage_report:
        description: "Coverage report file"
        required: false
        type: string

      ## Tags/flags for coverage report.
      coverage_flags:
        description: "Coverage flags"
        required: false
        type: string

      ## Whether to cache locally.
      cache_local:
        description: "Local cache"
        required: false
        type: boolean
        default: false

      ## Whether to cache remotely.
      cache_remote:
        description: "Remote cache"
        required: false
        type: boolean
        default: true

      ## Whether to cache using Actions.
      cache_action:
        description: "Action cache"
        required: false
        type: boolean
        default: true

      ## Whether to apply read-only mode to the cache.
      cache_read_only:
        description: "Read-only cache"
        required: false
        type: boolean
        default: false

      ## Whether to upload built artifacts.
      artifacts:
        description: "Artifacts"
        required: false
        type: boolean
        default: false

      ## Name of the output artifact.
      artifact:
        description: "Artifact"
        required: false
        type: string
        default: "gradle-build-output"

      ## Whether to run checks.
      checks:
        description: "Checks"
        required: false
        type: boolean
        default: true

      ## Whether to upload built reports.
      reports:
        description: "Reports"
        required: false
        type: boolean
        default: true

      ## Gradle version to use (defaults to wrapper version)
      gradle:
        description: "Gradle version"
        required: false
        type: string
        default: 'wrapper'

      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit

    secrets:
      SONAR_TOKEN:
        description: "Sonar token"
        required: false
      BUILDLESS_APIKEY:
        description: "Buildless API key"
        required: false
      CODECOV_TOKEN:
        description: "CodeCov token"
        required: false

env:
  JVM_VERSION: ${{ inputs.jvm || vars.JVM_VERSION || '17' }}
  JVM_DIST: ${{ inputs.jvm_dist || vars.JVM_DIST || 'adopt-hotspot' }}
  GRADLE_CACHE_LOCAL: ${{ inputs.cache_local }}
  GRADLE_CACHE_REMOTE: ${{ inputs.cache_remote }}
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.BUILDLESS_APIKEY }}

permissions:
  contents: read

jobs:
  ## Build Android app with Gradle
  build:
    name: "${{ inputs.label }}: Build"
    runs-on: ${{ inputs.runner || vars.RUNNER || vars.RUNNER_AMD64 || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    permissions:
      contents: "write"
      id-token: "write"
      checks: "write"
      pull-requests: "read"
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: ${{ inputs.network || 'audit' }}
      - name: "Setup: Checkout"
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: "Setup: Buildless"
        uses: buildless/setup@30e82389418c7f17046606183bc4c78b2c8913e0  # v1.0.2
      - name: "Setup: Cache"
        uses: buildless/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        if: inputs.cache_action
        with:
          path: |
            ./build
          key: ${{ runner.os }}-gradlebuild-${{ hashFiles('**/*.versions.toml', 'settings.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradlebuild-
      - name: "Setup: JDK ${{ env.JVM_VERSION }}"
        uses: buildless/setup-java@3232623d9c428cc5f228a01a2ae8d2d70f79775e # v4.0.0
        if: inputs.install_jvm
        with:
          distribution: ${{ env.JVM_DIST }}
          java-version: ${{ env.JVM_VERSION }}
      - name: "Setup: Android SDK"
        uses: buildless/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
        if: inputs.android
      - name: "Check: Gradle Wrapper"
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2.1.2
        if: inputs.checks
      - name: "Build: Gradle"
        continue-on-error: ${{ inputs.labs }}
        uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v2
        id: gradlebuild
        env:
          CI: true
          TEST_EXCEPTIONS: true
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          gradle-version: ${{ inputs.gradle || 'wrapper' }}
          cache-read-only: ${{ inputs.cache_read_only || false }}
          dependency-graph: generate-and-submit
          arguments: |
            ${{ inputs.action || 'build' }}
            ${{ inputs.flags }}
            -Pci=true
      - name: "Report: Codecov"
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        if: inputs.coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ inputs.coverage_report }}
          flags: ${{ inputs.coverage_flags }}
      - name: "Publish: Build Artifacts"
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v3
        if: inputs.artifacts
        with:
          name: ${{ inputs.artifact }}
          path: |
            ./build/libs/
            ./build/reports/
