name: "Bazel (Hardened)"

on:
  workflow_call:
    inputs:
      ## Job label
      label:
        description: "Label"
        default: "Bazel"
        required: false
        type: string

      ## Bazel command to run.
      command:
        description: "Command to run"
        default: "build"
        required: false
        type: string

      ## Bazel targets to run the command against.
      targets:
        description: "Targets"
        default: "//..."
        required: false
        type: string

      ## Bazel flags to pass.
      flags:
        description: "Flags"
        required: false
        type: string

      ## Runner machine to use.
      runner:
        description: "Runner"
        required: false
        type: string

      ## Whether to cache using Actions.
      cache_action:
        description: "Action cache"
        required: false
        type: boolean
        default: true

      ## Whether to apply read-only mode to the cache.
      cache_read_only:
        description: "Read-only cache"
        required: false
        type: boolean
        default: false

      ## Whether to upload built artifacts.
      artifacts:
        description: "Artifacts"
        required: false
        type: boolean
        default: false

      ## Whether to upload built reports.
      reports:
        description: "Reports"
        required: false
        type: boolean
        default: true

      ## Whether to generate and publish provenance info.
      provenance:
        description: "Provenance"
        required: false
        type: boolean
        default: false

      ## Bazel version to force
      version:
        description: "Bazel version"
        required: false
        type: string
        default: ""

      ## Bazel outputs for provenance and artifacts
      outputs:
        description: "Outputs list"
        required: false
        type: string
        default: ""

      ## Artifact name.
      artifact:
        description: "Artifact name"
        required: false
        type: string
        default: ""

      ## Artifact retention days.
      retention:
        description: "Artifact retention (days)"
        required: false
        type: number
        default: 7

      ## Artifact compression level,
      compression:
        description: "Artifact compression level"
        required: false
        type: number
        default: 6

      ## Whether to push artifacts and caches.
      push:
        description: "Push"
        required: false
        type: boolean
        default: false

      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit

    secrets:
      BUILDLESS_APIKEY:
        description: "Buildless API key"
        required: false
      BUILDBUDDY_APIKEY:
        description: "BuildBuddy API key"
        required: false

permissions:
  contents: read

jobs:
  ## Build with Bazel
  build:
    name: ${{ inputs.label }}
    runs-on: ${{ inputs.runner || vars.RUNNER || vars.RUNNER_AMD64 || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    permissions:
      contents: "read"
      id-token: "write"
      checks: "write"
      pull-requests: "read"
    env:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
      BUILDBUDDY_APIKEY: ${{ secrets.BUILDBUDDY_APIKEY }}
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: ${{ inputs.network || 'audit' }}
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup: Cache"
        uses: buildless/cache@e376f15c6ec6dc595375c78633174c7e5f92dc0e # v3
        if: inputs.cache_action
        with:
          path: |
            ~/.cache/bazel
          key: bazelbuild-${{ github.ref }}-${{ hashFiles('WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel', 'WORKSPACE.bzlmod') }}
          restore-keys:
            bazelbuild-${{ github.ref }}
            bazelbuild-
      - name: "Setup: Bazel"
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2.0.0
      - name: "Setup: Bazelisk"
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # v2.0.0
      - name: "Setup: Buildless"
        if: env.BUILDLESS_APIKEY != ''
        run: echo "build --remote_cache_header=x-api-key=${{ secrets.BUILDLESS_APIKEY }}" >> local.bazelrc
      - name: "Setup: BuildBuddy"
        if: env.BUILDBUDDY_APIKEY != ''
        run: echo "build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }}" >> local.bazelrc
      - name: "Setup: Bazel Version"
        if: inputs.version != ''
        run: echo "${{ inputs.version }}" > .bazelversion
      - name: "Build: Bazel"
        id: bazelbuild
        run: bazel ${{ inputs.command }} ${{ inputs.flags }} ${{ inputs.targets }}
      - name: "Build: Artifacts"
        if: inputs.artifacts && inputs.artifact != ''
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.outputs }}
          retention-days: ${{ inputs.retention }}
          compression-level: ${{ inputs.compression }}
          if-no-files-found: warn
      - name: "Build: Provenance Subjects"
        id: hash
        if: inputs.provenance && inputs.outputs != ''
        run: |
          set -euo pipefail
          sha256sum ${{ inputs.outputs }} > checksums
          echo "hashes=$(base64 -w0 < checksums)" >> "$GITHUB_OUTPUT"

  ## Provenance builder.
  provenance:
    needs: [build]
    if: inputs.provenance && inputs.push
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: ${{ inputs.push }}
