name: "Lint: Actions"

concurrency:
    group: lint-actions-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
  
on:
    ## Check actions on merge queue insertion
    merge_group: {}

    ## Allow this workflow to be re-used
    workflow_call: {}

    ## Check on release
    release:
        types: [created]

    ## Check on push to `main` if modified
    push:
        branches:
            - main
        paths:
            - ".github/workflows/*.yaml"
            - ".github/workflows/*.yml"
            - ".github/workflows/pkg/*/*.yaml"
            - ".github/workflows/pkg/*/*.yml"
            - "actions/*/*.yaml"
            - "actions/*/*.yml"
            - "containers/*/*.yaml"
            - "containers/*/*.yml"

    ## Check each PR change against `main`
    pull_request:
        paths:
            - ".github/workflows/*.yaml"
            - ".github/workflows/*.yml"
            - ".github/workflows/pkg/*/*.yaml"
            - ".github/workflows/pkg/*/*.yml"
            - "actions/*/*.yaml"
            - "actions/*/*.yml"
            - "containers/*/*.yaml"
            - "containers/*/*.yml"

env:
    GO_VERSION: '>=1.19.0'

permissions:
  contents: read

jobs:
    ## Task: Lint workflows in this respository with Actions Lint
    lint-workflow-actions:
        name: "Workflows"
        runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
        permissions:
            contents: "read"
            id-token: "write"
            checks: "write"
            pull-requests: "read"
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                egress-policy: audit

            - name: "Setup: Checkout"
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - name: "Setup: Go"
              uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
              with:
                go-version: ${{ vars.GO_VERSION || '' }}
            - name: "Setup: Action Linter"
              run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
            - name: "Lint: Actions"
              run: actionlint
