name: "Checks: Dependency Review"

on:
  pull_request: {}
  workflow_call:
    inputs:
      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: ${{ inputs.network || 'audit' }}
      - name: "Setup: Checkout Repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: "Check: Dependency Review"
        uses: actions/dependency-review-action@4901385134134e04cec5fbe5ddfe3b2c5bd5d976 # v4.0.0
