name: "Checks: Dependency Review"

on:
  pull_request: {}
  workflow_call:
    inputs:
      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit

permissions:
  contents: read

jobs:
  dependency-review:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: ${{ inputs.network || 'audit' }}
      - name: "Setup: Checkout Repository"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: "Check: Dependency Review"
        uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b # v4.2.5
