name: "Lint: YAML"

concurrency:
    group: lint-yaml-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
  
on:
    ## Check YAML on merge queue insertion
    merge_group: {}

    ## Check on release
    release:
        types: [created]

    ## Check on push to `main` if modified
    push:
        branches:
            - main
        paths:
            - ".github/workflows/*.yaml"
            - ".github/workflows/*.yml"
            - "workflows/*/*.yaml"
            - "workflows/*/*.yml"
            - "actions/*/*.yaml"
            - "actions/*/*.yml"
            - "containers/*/*.yaml"
            - "containers/*/*.yml"

    ## Check each PR change against `main`
    pull_request:
        paths:
            - ".github/workflows/*.yaml"
            - ".github/workflows/*.yml"
            - "workflows/*/*.yaml"
            - "workflows/*/*.yml"
            - "actions/*/*.yaml"
            - "actions/*/*.yml"
            - "containers/*/*.yaml"
            - "containers/*/*.yml"

permissions:
  contents: read

jobs:
    ## Task: Lint workflows in this respository with YAMLLint
    lint-workflows-yaml:
        name: "Workflows"
        runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
        permissions:
            contents: "read"
            id-token: "write"
            checks: "write"
            pull-requests: "read"
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
              with:
                egress-policy: audit

            - name: "Setup: Checkout"
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
            - name: "Setup: PNPM"
              uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
              with:
                version: ${{ env.PNPM_VERSION }}
            - name: "Setup: Node"
              uses: buildjet/setup-node@c7d4af42cfb6551248967ed0e51379dbae4cdefd # v3
              with:
                node-version: ${{ env.NODE_VERSION }}
                cache: "pnpm"

            - name: "Setup: NPM Credentials"
              run: |
                echo "@buf:registry=https://buf.build/gen/npm/v1" >> ~/.npmrc;
                echo "//npm.buf.build/:_authToken=${{ secrets.BUF_NPM_TOKEN }}" >> ~/.npmrc;
            - name: "Setup: Install Packages"
              run: pnpm install --frozen-lockfile
