name: "Checks: Scorecard"
on:
  branch_protection_rule: {}
  workflow_call:
    inputs:
      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: ["main"]

permissions: read-all

jobs:
  analysis:
    name: "Analysis: Scorecard"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: ${{ inputs.network || 'audit' }}
      - name: "Setup: Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: "Analysis: Run OSSF Scorecard Tool"
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - name: "Artifacts: Upload"
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Artifacts: Code Scanning"
        uses: github/codeql-action/upload-sarif@4dd16135b69a43b6c8efb853346f8437d92d3c93 # v3.26.6
        with:
          sarif_file: results.sarif
