name: "Containers: JVM"

on:
  merge_group: {}

  push:
    branches:
      - main
    paths:
      - containers/jvm
      - containers/jvm/*
      - containers/jvm/**/*
      - .github/workflows/container.yml
      - .github/workflows/containers.jvm.yml

  pull_request:
    paths:
      - containers/jvm
      - containers/jvm/*
      - containers/jvm/**/*
      - .github/workflows/container.yml
      - .github/workflows/containers.jvm.yml

permissions:
  contents: read

jobs:
  ## Build JVM Container
  build-jvm-container:
    name: "Image"
    uses: ./.github/workflows/container.yml
    secrets: inherit
    permissions:
      checks: write
      id-token: write
      contents: read
      packages: write
      pull-requests: write
    with:
      runner: ubuntu-latest
      image: elide-dev/build-infra/jvm
      path: containers/jvm
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
