name: "Lint: Actions"

on:
  workflow_call:
    inputs: {}

env:
    GO_VERSION: '>=1.19.0'

permissions:
  contents: read

jobs:
    ## Task: Lint workflows in a respository with Actions Lint
    lint-workflow-actions:
        name: "Workflows"
        runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
        permissions:
            contents: "read"
            id-token: "write"
            checks: "write"
            pull-requests: "read"
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
              with:
                egress-policy: audit
            - name: "Setup: Checkout"
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
            - name: "Setup: Go"
              uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
              with:
                go-version: ${{ vars.GO_VERSION || '' }}
            - name: "Setup: Action Linter"
              run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
            - name: "Lint: Actions"
              run: actionlint
