name: "Lint: Actions"

on:
  workflow_call:
    inputs:
      ## Network mode to apply.
      network:
        description: "Network"
        required: false
        type: string
        default: audit

env:
    GO_VERSION: '>=1.19.0'

permissions:
  contents: read

jobs:
  ## Task: Lint workflows in a respository with Actions Lint
  lint-workflow-actions:
    name: "Workflows"
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}
    permissions:
        contents: "read"
        id-token: "write"
        checks: "write"
        pull-requests: "read"
    steps:
        - name: "Setup: Harden Runner"
          uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
          with:
            egress-policy: ${{ inputs.network || 'audit' }}
        - name: "Setup: Checkout"
          uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
          with:
            persist-credentials: false
        - name: "Setup: Go"
          uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
          with:
            go-version: ${{ vars.GO_VERSION || '' }}
        - name: "Setup: Action Linter"
          run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
        - name: "Lint: Actions"
          run: actionlint
