name: "CI"

on:
  push:
    branches:
      - main
      - master

jobs:
  ## Triage: Determine checks to run for this changeset
  triage:
    name: "Triage"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'
          submodules: 'false'
          fetch-depth: 1
