name: "Build: Gradle (JVM)"

on:
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
    hello:
        name: "Test: Say Hello"
        runs-on: ubuntu-latest
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
            with:
              egress-policy: audit

          - name: "Emit Message"
            run: echo "Hello from reusable actions"
